### ISSUE TITLE
Please hint how to generate dev TLS certificate

### ISSUE THREAD

**Issue by paulvi** [havfo/SipCaller#1]
Please hint how to generate dev TLS certificate

```
localhost.cert.pem
localhost.key.pem
```

**Comment by havfo** [comment]
This can be generated using openssl:
$ openssl req -x509 -newkey rsa:4096 -keyout localhost.key.pem -out localhost.cert.pem -days 365

Just accept all defaults.

**Comment by paulvi** [comment]
Please accept PR #2 , then you or me can add this line

> openssl req -x509 -newkey rsa:4096 -keyout localhost.key.pem -out localhost.cert.pem -days 365
